// Attaches request-scoped context to every incoming request:
//   - request ID: reused from an upstream-trusted X-Request-Id if present,
//     otherwise generated by Fastify's genReqId (configured in server.ts).
//   - correlation ID: client-supplied X-Correlation-Id, used to stitch logs
//     across multiple gateway calls from the same client flow. Falls back to
//     the request ID when the client didn't send one, so it's never empty.
//   - a decorated `request.log` child logger (Fastify already gives us this
//     via genReqId) that includes both IDs on every log line for free.
// Both IDs are echoed back to the client and forwarded to backend services
// so a single request can be traced end to end.
import fp from 'fastify-plugin';
import type { FastifyPluginAsync } from 'fastify';
import { randomUUID } from 'node:crypto';
import { HEADERS } from '../constants/headers.js';

declare module 'fastify' {
  interface FastifyRequest {
    correlationId: string;
  }
}

export const requestContextPlugin: FastifyPluginAsync = fp(async (app) => {
  // Step 1: on every request, resolve the correlation ID and stash it.
  app.addHook('onRequest', async (request, reply) => {
    const incomingCorrelationId = request.headers[HEADERS.CORRELATION_ID];
    request.correlationId =
      (Array.isArray(incomingCorrelationId)
        ? incomingCorrelationId[0]
        : incomingCorrelationId) || request.id || randomUUID();

    // Step 2: echo both IDs back to the caller so they can correlate the
    // response with their own logs.
    reply.header(HEADERS.REQUEST_ID, request.id);
    reply.header(HEADERS.CORRELATION_ID, request.correlationId);

    // Step 3: rebind request.log so every subsequent log line in this
    // request's lifecycle carries both IDs automatically.
    request.log = request.log.child({
      requestId: request.id,
      correlationId: request.correlationId,
    });
  });
},
{ name: 'request-context' });
